/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eth.launcher;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "EthLauncher", version = "1.0", mixinStandardHelpOptions = true)
public class App implements Runnable {

  @Option(
      names = {"--config-file"},
      description = "Configuration file")
  String configFile = "";

  @Override
  public void run() {
    System.out.println(configFile);
  }

  public static void main(String[] args) {
    int exitCode = new CommandLine(new App()).execute(args);
    System.exit(exitCode);
  }
}
